# Generated by Django 5.2.7 on 2025-10-29 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do EPI')),
                ('categoria', models.CharField(choices=[('capacete', 'Capacete'), ('luva', 'Luva'), ('oculos', 'Óculos'), ('bota', 'Bota'), ('mascara', 'Máscara'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('validade', models.DateField(default=django.utils.timezone.now, verbose_name='Validade do EPI')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'ordering': ['nome'],
            },
        ),
    ]
