# Generated by Django 5.2.7 on 2025-10-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('setor', models.CharField(max_length=80)),
                ('foto_colaborador', models.ImageField(blank=True, null=True, upload_to='colaboradores/fotos/')),
            ],
        ),
    ]
